query1: 
  args:
      "User Category": [1, 2, 3]
  mapping:
      "User Category": [
        "Driver", 
        "Passenger",
        "Predestrian"
        ]

query2: 
  args:
      "Number of Displays": [3,4,5,6,7,8,9]
  mapping:
      "Number of Displays": [
        "Three", 
        "Four", 
        "Five", 
        "Six", 
        "Seven", 
        "Eight", 
        "Nine"
        ]

query3:
  args:
      "Accident Situation": [1, 2, 3, 4, 5, 6]
  mapping:
      "Accident Situation": [
        "On roadway",
        "On emergency lane",
        "On shoulder",
        "On sidewalk",
        "On bike lane",
        "On other special lane"
        ]
query4:
  args:
      "Number of Displays": [3,4,5,6,7,8,9]
  mapping:
      "Number of Displays": [
        "Three", 
        "Four", 
        "Five", 
        "Six", 
        "Seven", 
        "Eight", 
        "Nine"
        ]

query5:
  args:
      "Road Category" : [1,2,3,4,5,6,7]
  mapping:
      "Road Category" : [
        "Motorway",
        "National road",
        "Departmental road",
        "Local road",
        "Outside public network",
        "Publicly accessible parking lot",
        "Urban metropolitan roads"
        ]
query6:
  args:
      "Gender": [1, 2]
  mapping:
      "Gender": [
        "Masculine",
        "Feminine"
        ]
query7:
  args:
      "Number of Displays": [3,4,5,6,7,8,9]
  mapping:
      "Number of Displays": [ 
        "Three", 
        "Four", 
        "Five", 
        "Six", 
        "Seven", 
        "Eight", 
        "Nine"
        ]
query8:
  args:
      "Atmospheric Conditions": [1, 2, 3, 4, 5, 6, 7, 8]
  mapping: 
      "Atmospheric conditions" : [     
        "Normal",
        "Light rain",
        "Heavy rain",
        "Snow - hail",
        "Fog - smoke",
        "Strong wind - storm",
        "Blinding weather",
        "Overcast"
        ]
query9:
  args:
      "Severity": [1, 2, 3, 4]
  mapping: 
      "Severity": [    
        "Unharmed",
        "Fatal",
        "Hospitalized injury",
        "Minor injury"
        ]
query10:
  args:
      "3rd Safety Equipment": [1, 2, 3, 4, 5, 6, 7, 8]
  mapping : 
      "3rd Safety Equipment": [    
      "Seatbelt",
      "Helmet",
      "Child restraint system",
      "Reflective vest",
      "Airbag (2-wheel/3-wheel)",
      "Gloves (2-wheel/3-wheel)",
      "Gloves + Airbag (2-wheel/3-wheel)",
      "Not determinable"
      ]
query11:
  args:
      "Severity": [1, 2, 3, 4]
  mapping: 
      "Severity": [  
        "Unharmed",
        "Fatal",
        "Hospitalized injury",
        "Minor injury"
        ]
query12:
  args:
      "User Category": [1, 2, 3]
  mapping:
      "User Category": [
        "Driver", 
        "Passenger", 
        "Predestrian"
        ]



